### PR TITLE
Switch out `atty` for `is-terminal`

### PR DESCRIPTION
**Pull request by Porges**
Draft for now, switching out `atty` for `is-terminal` per #228

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I stumbled across this due to a `cargo-deny` notification for `atty` on one of my crates... So let me ask: What's the status here? :laughing:

**Comment by zkat** [comment]
I'll totally take a non-draft version of this PR (with concrete dep versions, yes)

**Comment by matthiasbeyer** [comment]
Are you fine with the git dependencies?
If not, https://github.com/zkat/supports-unicode/pull/4 and https://github.com/zkat/supports-hyperlinks/pull/3 should probably be merged first and of course also released... :thinking:

**Comment by Porges** [comment]
Updated this PR to match updated versions of the https://github.com/zkat/supports-unicode/pull/4 and https://github.com/zkat/supports-hyperlinks/pull/3 PRs. Once those are merged this can change to point to the released crates.

**Comment by zkat** [comment]
@Porges Just released `supports-hyperlinks@2.0.0` and `supports-unicode@2.0.0` with the is_terminal changes.

**Comment by Porges** [comment]
@zkat and updated to match 🙂

**Comment by zkat** [comment]
This is released as part of miette@5.6.0 :)

**Comment by Porges** [comment]
@zkat thanks!

**Pull request merged**
